Play: merged m3u and mus, made all variables camelCase.
Added builtin support for my 'm3u' and 'mus' scripts in the form of '-c' (create mode) and '-f' (format mode) respectively.
Decided to make all variables camelCase for better distinction from functions, which are named in snake_case.

diff --git a/play b/play
--- a/play
+++ b/play
@@ -6,42 +6,50 @@
 # TODO: Shuffle
 
 mode="fuzzy"
-multi_select=""
+multiSelect=""
 loop=""
-playlist_extension="m3u"
+playlistExtension="m3u"
 defaultDir=""
 
 show_help() {
   echo -e "Usage: play [-h -d -l -m -p -pe ] [args] [/media/directory]\n"
   echo -e "Flags:"
   echo "  -h:     Display this message."
+  echo "  -c:     Creates an mpv playlist file."
   echo "  -d:     Searches by directories."
+  echo "  -f:     Formats filenames."
   echo "  -l:     Enables looping."
   echo "  -m:     Enables multiple selections using Tab."
   echo "  -p:     Searches by file extension."
   echo "  -e:     Specify what file extension to use. (Defaults to m3u)"
 }
 
-while getopts "hdlmpe:" opt; do
+while getopts "hcdflmpe:" opt; do
   case ${opt} in
     h)
       show_help
       exit 1
       ;;
+    c)
+      mode="create"
+      ;;
     d)
       mode="dirs"
+      ;;
+    f)
+      mode="format"
       ;;
     l)
       loop="--loop-playlist"
       ;;
     m)
-      multi_select="-m"
+      multiSelect="-m"
       ;;
     p)
       mode="playlist"
       ;;
     e)
-      playlist_extension="$OPTARG"
+      playlistExtension="$OPTARG"
       ;;
     \?)
       show_help
@@ -51,12 +59,41 @@ while getopts "hdlmpe:" opt; do
 done
 shift $((OPTIND -1))
 
+create_playlist() {
+  # Directory confirmation.
+  echo "Create a playlist in $defaultDir? (y/n)"
+  read dirConfirm < /dev/tty
+
+  # Parse confirmation/denial.
+  if [ "$dirConfirm" == "y" ]; then
+    # Grab current directory name.
+    dirName=${PWD##*/}
+    dirName=${result:-/}
+
+    # Generate playlist name based on input or dir name.
+    # Removes '.m3u' if provided to prevent '.m3u.m3u'.
+    fileName=$(echo "$dirName" | sed -e 's/.m3u//g')
+
+    # Select play order with fzf.
+    echo "$(fzf -m)" > $fileName.m3u
+
+    # Print contents of playlist file for error checking.
+    cat $fileName.m3u;
+  elif [ "$dirConfirm" == "n" ]; then
+    echo "Nothing to do."
+    exit 1
+  else
+    echo "Error: Please confirm or deny changes."
+    create_playlist
+  fi
+}
+
 dirs_mode () {
   # Create a temporary playlist file.
   playlist=$(mktemp "$defaultDir"/.temp_playlist_XXXXXX.m3u)
 
   # Select directories and echo all non-playlist files to temp playlist.
-  find $(fzf $multi_select) -type f ! -name "*.$playlist_extension" > "$playlist"
+  find $(fzf $multiSelect) -type f ! -name "*.$playlistExtension" > "$playlist"
 
   # Ensure playlist is non-empty.
   if [ -s "$playlist" ]; then
@@ -70,12 +107,12 @@ dirs_mode () {
 }
 
 multi_select () {
-  if [ -n "$multi_select" ]; then
+  if [ -n "$multiSelect" ]; then
     # Create a temporary playlist file.
     playlist=$(mktemp "$defaultDir"/.temp_playlist_XXXXXX.m3u)
 
     # Echo selection to playlist.
-    fzf $multi_select > "$playlist"
+    fzf $multiSelect > "$playlist"
 
     # Ensure playlist is non-empty.
     if [ -s "$playlist" ]; then
@@ -94,16 +131,70 @@ multi_select () {
   fi
 }
 
+format_name() {
+  # Create a temporary file with all file names.
+  tmp=$(mktemp /tmp/temp_list_XXXXXX.txt)
+  echo "$(find * -type f)" > "$tmp"
+
+  # Loop until every line of the tmp file is read.
+  while read -r line; do
+    # Format file name.
+    origin="$line"
+    pass1=$(echo "$origin" | sed 's/\ \[.*\]//g') # Remove ' [anything in here]'.
+    pass2=$(echo "$pass1" | sed 's/[()]//g') # Remove any parenthesis.
+    pass3=${pass2//[' ']/_} # Replace any spaces with underscores.
+    pass4=$(echo "${pass3,,}") # Replace all caps with lowercase characters.
+
+    # Display each stage of the file name for confirmation.
+    echo -e "Original:\n$origin\n"
+    echo -e "1st pass:\n$pass1\n"
+    echo -e "2nd pass:\n$pass2\n"
+    echo -e "3rd pass:\n$pass3\n"
+    echo -e "4th pass:\n$pass4\n"
+
+    # Require user confirmation.
+    echo "Confirm? (y/n/a)"
+
+    # Prevent asking for confirmation after agreeing to all ('a').
+    if [ -z "$skip" ]; then
+      read confirm < /dev/tty
+    fi
+
+    # Parse confirmation/denial.
+    if [ "$confirm" == "y" ]; then
+      echo -e "Confirmed.\n"
+      mv "$origin" "$pass4"
+    elif [ "$confirm" == "n" ]; then
+      echo -e "Denied.\n"
+    elif [ "$confirm" == "a" ]; then
+      # Invalidates the confirmation `if` statement and accepts all changes.
+      skip="on"
+      confirm="y"
+    else
+      echo "Confirmation required."
+      rm "$tmp"
+      exit 1
+    fi
+  done < "$tmp"
+  rm "$tmp"
+}
+
 mode_select () {
   case $mode in
+    create)
+      create_playlist
+      ;;
     dirs)
       find * -type d -print | dirs_mode
       ;;
     playlist)
-      find * -name "*.$playlist_extension" | multi_select
+      find * -name "*.$playlistExtension" | multi_select
       ;;
     fuzzy)
       multi_select
+      ;;
+    format)
+      format_name
       ;;
   esac
 }
